name: odosa
description: "A new Flutter project."
publish_to: "none"
version: 2.2.0+2

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0 # Database untuk Android
  sqflite_common_ffi: ^2.3.0 # Database untuk Linux & Windows
  path_provider: ^2.1.2 # Penanganan direktori cross-platform
  path: ^1.9.0
  intl: ^0.19.0 # Formatting mata uang (Rp)
  flutter_riverpod: ^2.5.1 # State management
  fl_chart: ^1.2.0
  csv: ^6.0.0
  file_picker: ^8.1.2
  shared_preferences: ^2.5.5
  google_sign_in: ^7.2.0
  googleapis: ^17.0.0
  googleapis_auth: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
