name: odosa
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0+2

environment:
  sdk: ^3.13.3
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  csv: ^5.1.1
  http: ^1.2.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.16.0
flutter:
  uses-material-design: true
